Fix validator: use Colors.BOLD instead of non-existent CYAN
AttributeError: Colors has no attribute 'CYAN'
Changed to Colors.BOLD for command display.